### PR TITLE
Updated the Gemspec to Suit Rails 4.0.0.rc1

### PR DESCRIPTION
**Pull request by saurabhbhatia**
Updated the versions of ActiveSupport and ActiveModel to suit Rails 4.0.0.rc1.

### CODE REVIEW

**Comment by felixclack** [comment]
Thanks for this.

Seeing as Rails 4 is now officially released, do you want to update this again?

**Comment by saurabhbhatia** [comment]
Sure, let me update and send a fresh pull request, we can close this one.

**Comment by felixclack** [comment]
Thanks.

**Comment by saurabhbhatia** [comment]
My pleasure :+1:

**Pull request merged**
